### PR TITLE
CAP: Avoid msg_type button regression

### PR DESCRIPTION
**Pull request by biplovbhandari**
@flavour Please merge

### CODE REVIEW

**Comment by flavour** [comment]
I see no need to add this extra variable

**Comment by nursix** [comment]
I see no extra variable here?

**Comment by flavour** [comment]
ok, this is even 2 less :)

**Comment by nursix** [comment]
Yup, and it looks cleaner than before - now all variables are initialized for all branches.

May have been a bit premature to close this.

**Pull request closed without merging**
