### PR TITLE
configuration of message identifier task 1.1

### PR DESCRIPTION
**Pull request by biplovbhandari**
true for info template fixed

### CODE REVIEW

**Comment by flavour** [comment]
All fine other than the instance-specific settings being in the general config...comment these out & we're good to merge :)

**Comment by biplovbhandari** [comment]
then we allow user to make changes on templates/<>/config.py ?

**Comment by nursix** [comment]
Maybe a more plausible commit message? "Task 1.1" reference is not very conclusive outside of the PM context

**Comment by flavour** [comment]
Right, good to refer to the spreadsheet:
https://docs.google.com/spreadsheets/d/1N9xUqZQhignq7QM_7CtrV4zv86sq4lMdJj81IQuch3Y/edit#gid=0

**Pull request closed without merging**
