### PR TITLE
[Fix]: Representation of item name in autocomplete widget

### PR DESCRIPTION
**Pull request by raj454raj**
http://127.0.0.1:8000/eden/req/req/1/req_item --> Add Item to request , Autocomplete for Item field not working before. (Giving link of localhost because demo is not working ;) )

### CODE REVIEW

**Comment by nursix** [comment]
Fix at the wrong end - this was just changed into fieldname as "label" isn't standard. Please fix the corresponding controller.

**Comment by nursix** [comment]
If you change it back into "label", it will not work with e.g. org_site_search_ac and org_search_ac. So, either you fix /all/ search_ac's to use "label" (then you can hardcode it) - or you fix the particular search_ac that uses "label" to use the fieldname.

To me, fieldname is more consistent and less fragile.

**Comment by nursix** [comment]
...less fragile because the ac handler allows to extract additional fields - and hardcoding anything would allow name collisions, whereas fieldname would at most "collide" with itself ;)

**Comment by nursix** [comment]
Like this: https://github.com/nursix/eden/commit/26f4d3a7a68844321510f29b7a38a3f70d46ffd9

**Comment by raj454raj** [comment]
Okay :+1:

**Comment by nursix** [comment]
I think the problem here is the inconsistency between all the different search_ac's (implemented by different people). Using the fieldname is more or less intuitive, and obviously how most of the devs interpret the overall concept - so let's just stick with this for consistency reasons.

Thanks however for pointing to the issue, I had stumbled over this some time ago, but apparently didn't see the whole picture then.

**Comment by nursix** [comment]
Shall I revoke my commit, so you can update this PR?

**Comment by nursix** [comment]
...this would give you a trunk commit ;)

**Comment by raj454raj** [comment]
@nursix : done.

**Comment by nursix** [comment]
Err...not quite the same thing, is it?

Should be like:

    record = {"id": row.id,
                   fieldname: row[fieldname],
                   }

...and remove the JS changes.

**Comment by raj454raj** [comment]
Hold on: This time I need to apologize sorry.

**Comment by nursix** [comment]
Apologizing again? :D

**Comment by raj454raj** [comment]
@nursix :done.

**Comment by nursix** [comment]
Good :+1: ready to merge.

**Pull request merged**
