### PR TITLE
SSF Bug Fix

### PR DESCRIPTION
**Pull request by hitesh96db**
Filtering doesn't work with some fields here.
http://sunflower.sahanafoundation.org/eden/project/project/1/task 
For eg: milestone.

### CODE REVIEW

**Comment by flavour** [comment]
This will fix that URL but break the more common (at least for me) /project/task/x URLs
We need to detect function & change accordingly.
NB One of the changes was already in a function != project

**Comment by nursix** [comment]
Ahm - it should actually work just fine for project/task/x? ("task" prefix is automatically detected as master if it matches the master alias).

**Comment by hitesh96db** [comment]
Yes, ^ I tried that, it seems to work fine

**Comment by nursix** [comment]
It should, because "~.selector" is equal to "alias.selector" is alias is master.

**Comment by flavour** [comment]
ok, so I learnt something...but one of the fixes still seems wrong since it fixes for project/project/task yet is behind a function!= "project"?

**Comment by nursix** [comment]
Question is though whether you really need to prefix it at all - normally, when you configure the filters for a table, it will always be the master table...so why the need for an explicit prefix here?

**Comment by nursix** [comment]
Just *if* you prefix it, then ~.* and master.* or no prefix is all the same thing.

**Comment by nursix** [comment]
But I still don't see the point of prefixing in a filter widget configuration (there is actually a reason why you do not need that - the table is defined by s3db.configure(tablename, ...))

**Comment by hitesh96db** [comment]
But then filter forms won't work when viewed in components like project/project/id/task ?

**Comment by hitesh96db** [comment]
Because these filters are meant to be resolved with the master "task" table and not "project"

**Comment by nursix** [comment]
Ahm - actually not: filter widgets are resolved against the target resource, not the master resource - and should automatically be prefixed. This would only fail if the request goes to the wrong URL (i.e. ajax URL misconfigured).

**Comment by nursix** [comment]
I'll check it. Seems like the wrong fix (but it shouldn't harm, however).

**Comment by nursix** [comment]
Yeah - as I suspected it: your fix is "correct", but in the wrong place. 

What you do here should actually happen automatically - namely: we do pass in the component alias to the filter form so that it can prefix any non-prefixed selector in filter widgets correctly for the current component:

https://github.com/flavour/eden/blob/master/modules/s3/s3crud.py#L1180

But in this case of "task_milestone.milestone_id", the selector /does/ already have a prefix (="task_milestone"), so it was skipped - which is a bit insufficient logic: of course this must check whether it is the /right/ prefix, not just any prefix.

I pushed a fix for that.

**Comment by nursix** [comment]
So, @flavour : no need to learn anything new ;) filter widgets do not need a component prefix.

**Comment by flavour** [comment]
So this PR is deprecated?

**Comment by hitesh96db** [comment]
No, wait...the other part, that is, removing the "Assigned to" field is required

**Comment by hitesh96db** [comment]
I'll remove the "top" part of the commit, i.e, the "task" part

**Comment by hitesh96db** [comment]
@flavour done

**Comment by nursix** [comment]
Yes. deprecated after you merged the fix I pushed.

**Pull request merged**
